apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mk-rhtap-app
  janus-idp.io/tekton: mk-rhtap-app
  backstage.io/kubernetes-id: mk-rhtap-app
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mk-rhtap-app
resources:
- deployment.yaml
- route.yaml
- service.yaml
